version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: eat-me-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eat_me
      MYSQL_USER: eat_me
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - eat-me-network

networks:
  eat-me-network:
    driver: bridge
